version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./test-jira-page.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  # Простой HTTP сервер для тестирования расширения
  test-server:
    image: python:3.9-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: python -m http.server 3000
    restart: unless-stopped
