
ALTER DATABASE jiradb SET timezone TO 'UTC';

GRANT ALL PRIVILEGES ON DATABASE jiradb TO jira;
GRANT ALL PRIVILEGES ON SCHEMA public TO jira;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO jira;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO jira;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO jira;

SELECT 'Jira database initialized successfully' as status;
